apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: agnostic-api
  name: agnostic-api
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: agnostic-api
    spec:
      containers:
      - image: toprocklabs/agnostic-api:v0.1
        name: agnostic-api
        ports:
        - containerPort: 3000
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
